### ISSUE TITLE
Possible to update to 1.7.5

### ISSUE THREAD

**Issue by viion** [liinko/FFXIV_TexTools2#10]
Hello!

The current repository seems to be 1.7.0, so it is crashing on launch, I think for something that was fixed in 1.7.5 according to the change log here: http://ffxivtextools.dualwield.net/change_log.html

Would it be possible to get the repo updated to 1.7.5?

Regards and great work!

**Comment by liinko** [comment]
I seem to have forgotten to do a commit, I've already made some more changes since then, but the master branch should now be a little more than up to date, pushed as 1.8 WIP for now.
