### ISSUE TITLE
Doesn't seem to copy required dx files when building

### ISSUE THREAD

**Issue by viion** [liinko/FFXIV_TexTools2#13]
By default if you download the repo and try build you will get this error:

```
System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 
'FFXIV_TexTools2.MainWindow' that matches the specified binding constraints threw 
an exception.' Line number '10' and line position '5'. ---> System.DllNotFoundException: 
Unable to load DLL 'sharpdx_direct3d11_1_effects_x64.dll': The specified module could 
not be found. (Exception from HRESULT: 0x8007007E)
```

You have to copy these files across to your build folder.

Anyway to automate this?

**Comment by liinko** [comment]
Yes, you can go into the files properties 
![image](https://user-images.githubusercontent.com/5404487/37259961-54f025f8-255b-11e8-9028-54adbb6de505.png)

Then change **Copy to Output Directory** to **Copy always**, that should automate the process.
![image](https://user-images.githubusercontent.com/5404487/37259976-a4c482ea-255b-11e8-899d-db9e36d9c974.png)

**Comment by viion** [comment]
Perfect! Thank you
