### ISSUE TITLE
 question with decompressed exd data

### ISSUE THREAD

**Issue by kaedeair** [liinko/FFXIV_TexTools2#5]
hello liinko:
I wanna to know wheather the offset of  item details in item.exd will change their value after 0a000.dat version update.
I use old 0a000.dat it will be error,but when use the new one,it does work.
I compared the decompressed exd data and found the offset value of  item details changed.
Hope to answer doubts.   : )

**Comment by liinko** [comment]
Yes, it can change and it has changed before. It is not likely that it will change often but if they add any new information or remove any information from an item's details it will have to be corrected by changing the values in MakeItemsList method of the ExdReader class.
